- name: install nginx
  yum: name=nginx state=present

- name: put nginx.conf
  template: src=roles/nginx/templates/nginx.conf dest=/etc/nginx/nginx.conf

- name: put conf.d/default.conf
  template: src=roles/nginx/templates/default.conf dest=/etc/nginx/conf.d/default.conf

- name: put conf.d/virtual.conf
  template: src=roles/nginx/templates/virtual.conf dest=/etc/nginx/conf.d/virtual.conf

- name: set auto start nginx
  command: chkconfig nginx on

- name: restart nginx
  command: service nginx restart
